---

env:
  browser: true
  es6: true
  jest: true
  jquery: true
  node: true
  worker: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  array-bracket-newline:
    - error
    - multiline: true
      minItems: 2
