---

name: lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install mdl
        run: |
          sudo apt-get update \
              && sudo apt-get install -y rubygems \
              && sudo gem install mdl
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Cache for Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: yarn install
        run: yarn install

      - name: yarn 
        run: sudo yarn global add eslint

      - name: yarn add JSONlint
        run: sudo yarn global add jsonlint

      - name: Lint JavaScript files
        run: eslint "lambda-functions/lib/**/*.js"
        if: always()

      - name: Lint JSON files
        run: |
          find . \
              -type f \
              -name "*.json" \
              -print0 \
              | xargs -n 1 -0 \
                  jsonlint --quiet --compact

