---

name: lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install mdl
        run: |
          sudo apt-get update \
              && sudo apt-get install -y rubygems \
              && sudo gem install mdl

      - name: yarn install
        run: yarn install

      - name: yarn 
        run: yarn add eslint

      - name: Lint JavaScript files
        run: yarn eslint "lambda-functions/lib/**/*.js"
        if: always()

      - name: Lint JSON files
        run: |
          find . \
              -type f \
              -name "*.json" \
              -print0 \
              | xargs -n 1 -0 \
                  jsonlint --quiet --compact
